version: 2
jobs:
  build:
    one:
      docker:
        - image: circleci/ruby:2.4.1-jessie
      steps:
        - checkout
        - run: echo "Hello world"
  build:
    two:
      docker:
        - image: circleci/ruby:2.4.1-jessie
      steps:
        - checkout
        - run: echo "Hello world"